version: '3.1'

services:
  springboot:
    image: arunbabu1322/spring_boot_mongo_db:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=admin
    - MONGO_DB_PASSWORD=adminadmin
    ports:
      - 9101:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=adminadmin
    restart: always
    networks:
    - springappnetwork


networks:
  springappnetwork:
    driver: bridge
